// <auto-generated />
namespace TP1_65069.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Birthdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Birthdate));
        
        string IMigrationMetadata.Id
        {
            get { return "201609241826594_Birthdate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
